spring:
  application:
    name: estructura
  data:
    mongodb:
      uri: mongodb+srv://joooohanenciso:kRyEZZOUseC0pSC7@cluster0.hw1quvh.mongodb.net/peluqueria_canina?retryWrites=true&w=majority&appName=Cluster0

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/plain
    min-response-size: 1024
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

jwt:
  secret: your_secure_secret_key_here_that_is_at_least_256_bits_long_1234567890abcdef
  expiration: 604800000
